using Cinemachine;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public interface IInteractable
{
    void OnInteract(PlayerInputManager messageSource);
}

public interface IDamageable
{
    public float Health { get; set; }
    float GetMaxHealthDefault(float MAX_HEALTH_DEFAULT = 1.0f); //Do not override
    public void OnDamageRecieved(float damage);
}

public interface ICanBeDisabled
{
    void OnDisableInteract();
}

//For anything that wants to be triggerable
public interface IEventListener
{
    void OnActivated();
}

//For anything that wants to appear on a terminal
public interface ITerminalListener : IEventListener
{
    public int IDGroup { get; set; } //Interface has field IDGroup, implementing classes can have ID field this hooks into
    public Sprite TerminalButtonIcon { get; set; } //This will allow buttons to be generated by terminals that can see compatible listeners
}